//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnderstandingEFApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblEmployeeSalary
    {
        public int transaction_number { get; set; }
        public Nullable<int> employee_id { get; set; }
        public Nullable<int> salary_id { get; set; }
        public Nullable<System.DateTime> salDate { get; set; }
    
        public virtual tblEmployee tblEmployee { get; set; }
        public virtual tblSalary tblSalary { get; set; }
    }
}
