//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnderstandingEFApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSalary
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblSalary()
        {
            this.tblEmployeeSalaries = new HashSet<tblEmployeeSalary>();
        }
    
        public int id { get; set; }
        public Nullable<double> basic { get; set; }
        public Nullable<double> HRA { get; set; }
        public Nullable<double> DA { get; set; }
        public Nullable<double> deductions { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblEmployeeSalary> tblEmployeeSalaries { get; set; }
    }
}
